#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
    update-ca-certificates --fresh
    chmod +x /usr/local/sbin/update-p11-kit-symlinks
    ln -s /lib/systemd/system/p11-kit-proxy-updater.service /etc/systemd/system/multi-user.target.wants/p11-kit-proxy-updater.service


fi
# End automatically added section
