#!/bin/sh
set -e
# Automatically added by dh_installudev

update-ca-certificates --fresh
rm /etc/systemd/system/multi-user.target.wants/p11-kit-proxy-updater.service


# End automatically added section
