#!/bin/sh
set -e
# Automatically added by dh_installudev
if [ "$1" = configure ]; then
	for u in /usr/share/NAME/*.crt; do 
        ln -s /usr/share/NAME/$u /usr/share/ca-certificates/mozilla/$u
    done
    update-ca-certificates
fi
# End automatically added section
